name: "❓ Question"
description: Ask a question about using or developing this project
title: "[Question] <short description>"
labels: [question]
type: question
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## Question

        Please provide details about your question.

  - type: input
    id: summary
    attributes:
      label: Question summary
      description: Briefly state your question.
      placeholder: "How do I authenticate with the API?"

  - type: textarea
    id: details
    attributes:
      label: Details
      description: Add more context or background for your question.
      placeholder: "I am trying to use the /api/v1/public/organizations/projects endpoint..."

  - type: textarea
    id: files
    attributes:
      label: Related files or code
      description: List any relevant files, code snippets, or links.
      placeholder: "openapi.yaml, example request payload"
